# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96ea6d2a3a473009be142d557d130f70c3d0afd586765d2c342a94c91e2524fcc92bae466528cb042361a84f89d0efa31633e1a845c25bcd0918e5657035cdfb

test:
  secret_key_base: f76ebc2bfac07167a4b9b2b436cf8a3b2a9c62bbb5d8337fc35783cc3312f611403e4db6e0c3ef34f54688a837bbc1b8f67ae1b9a5ffcad206797c89ca8c650c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
